import { InboxConfig } from "./inbox-types";

export const whatsappConfig: InboxConfig = {
  variant: "whatsapp",
  title: "WhatsApp",
  subtitle: "16 aktif konuşma",
  statusText: "Bot aktif",
  accent: "green",
  activeChannelLabel: "WhatsApp",
  customerName: "Zeynep Kaya",
  customerInitials: "ZK",
  customerStatus: "Bot aktif",
  quickActions: ["Fiyat listesi gönder", "Uygun saat öner", "İnsana devret"],
  chats: [
    {
      id: "chat-zeynep",
      name: "Zeynep Kaya",
      initials: "ZK",
      message: "Merhaba, cilt bakımı için fiyat alabilir miyim?",
      time: "11:01",
      unread: 2,
      active: true,
      tag: "Yeni müşteri",
      channel: "WhatsApp",
    },
    {
      id: "chat-merve",
      name: "Merve Aydın",
      initials: "MA",
      message: "Yarın için uygun saat var mı?",
      time: "10:42",
      unread: 0,
      active: false,
      tag: "Sıcak lead",
      channel: "WhatsApp",
    },
    {
      id: "chat-berna",
      name: "Berna Demir",
      initials: "BD",
      message: "Kaş laminasyonu ne kadar sürüyor?",
      time: "10:16",
      unread: 1,
      active: false,
      tag: "Fiyat soruyor",
      channel: "WhatsApp",
    },
    {
      id: "chat-esra",
      name: "Esra Çelik",
      initials: "EÇ",
      message: "Cumartesi boşluk var mı?",
      time: "09:58",
      unread: 0,
      active: false,
      tag: "Randevu adayı",
      channel: "WhatsApp",
    },
  ],
  messages: [
    {
      from: "them",
      text: "Merhaba, cilt bakımı için fiyat alabilir miyim?",
      time: "11:01",
    },
    {
      from: "me",
      text: "Merhaba, elbette. Cilt bakımı için güncel fiyatlarımızı paylaşabilirim.",
      time: "11:02",
    },
    {
      from: "me",
      text: "Size uygun saatlere göre randevu oluşturabilirim.",
      time: "11:03",
    },
  ],
  customerCard: {
    customerName: "Zeynep Kaya",
    customerPhone: "+90 5xx xxx xx xx",
    labels: ["Yeni müşteri", "WhatsApp", "Fiyat soruyor"],
    interestTitle: "Cilt Bakımı",
    interestDescription: "Fiyat sorusu ile başladı",
    nextAppointmentTitle: "Henüz randevu yok",
    nextAppointmentDescription:
      "Bot uygun saat önerirse rezervasyona dönme ihtimali yüksek.",
    lastActivity: "11:01’de fiyat sordu. 11:03 itibarıyla bot randevu teklifine geçti.",
    botNote:
      "Kullanıcı fiyat ve hizmet bilgisi istiyor. Uygun saat gösterilirse rezervasyona dönme ihtimali yüksek.",
  },
};

export const instagramConfig: InboxConfig = {
  variant: "instagram",
  title: "Instagram DM",
  subtitle: "9 aktif mesaj",
  statusText: "DM akışı aktif",
  accent: "pink",
  activeChannelLabel: "Instagram",
  customerName: "Dilan Aras",
  customerInitials: "DA",
  customerStatus: "İnsan devraldı",
  quickActions: ["DM şablonu gönder", "Randevuya yönlendir", "Lead etiketi ekle"],
  chats: [
    {
      id: "ig-dilan",
      name: "Dilan Aras",
      initials: "DA",
      message: "Protez tırnak fiyatı nedir acaba?",
      time: "12:14",
      unread: 1,
      active: true,
      tag: "DM lead",
      channel: "Instagram",
    },
    {
      id: "ig-selin",
      name: "Selin K.",
      initials: "SK",
      message: "Story’den geldim, yarın boşluk var mı?",
      time: "11:48",
      unread: 0,
      active: false,
      tag: "Sıcak lead",
      channel: "Instagram",
    },
    {
      id: "ig-tugce",
      name: "Tuğçe Nur",
      initials: "TN",
      message: "Kalıcı oje ne kadar kalıyor?",
      time: "11:19",
      unread: 2,
      active: false,
      tag: "Bilgi istiyor",
      channel: "Instagram",
    },
    {
      id: "ig-buse",
      name: "Buse A.",
      initials: "BA",
      message: "Reels’te gördüm, fiyat alabilir miyim?",
      time: "10:55",
      unread: 0,
      active: false,
      tag: "Reels lead",
      channel: "Instagram",
    },
  ],
  messages: [
    {
      from: "them",
      text: "Merhaba, protez tırnak fiyatı nedir acaba?",
      time: "12:14",
    },
    {
      from: "me",
      text: "Merhaba, protez tırnak için güncel fiyatlarımızı paylaşabilirim.",
      time: "12:15",
    },
    {
      from: "me",
      text: "İsterseniz uygun gün ve saatlere göre direkt randevu da oluşturabiliriz.",
      time: "12:16",
    },
  ],
  customerCard: {
    customerName: "Dilan Aras",
    customerPhone: "@dilanaras",
    labels: ["Instagram", "DM lead", "Protez tırnak"],
    interestTitle: "Protez Tırnak",
    interestDescription: "Reklamdan geldi, fiyat soruyor",
    nextAppointmentTitle: "Henüz randevu yok",
    nextAppointmentDescription:
      "DM konuşması rezervasyona çevrilebilir, yüksek potansiyel.",
    lastActivity: "12:14’te fiyat sordu, 12:16’da randevu yönlendirmesi yapıldı.",
    botNote:
      "Kullanıcı satın almaya yakın görünüyor. Uygun saat ve kampanya bilgisi verilirse dönüşüm ihtimali yüksek.",
  },
};